# Generated by Django 2.0.7 on 2019-02-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='bio',
        ),
    ]
