# Generated by Django 2.0.7 on 2019-02-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
