# Generated by Django 2.0.7 on 2019-02-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='Username'),
        ),
    ]
